#!/usr/bin/env bash
#$ -o /medpop/afib/skhurshid/lvm_gwas/scores/seg_prs4/log/$JOB_NAME.$JOB_ID.log
#$ -e /medpop/afib/skhurshid/lvm_gwas/scores/seg_prs4/err/$JOB_NAME.$JOB_ID.err
#$ -N seg_prs4
#$ -cwd
#$ -t 1-22
#$ -l h_vmem=40g
#$ -l h_rt=15:00:00
#$ -l h=!ugerbm-c00*

##1-22
echo "=========================================================="
echo "Starting on       : $(date)"
echo "Running on node   : $(hostname)"
echo "Current directory : $(pwd)"
echo "Current job ID    : $JOB_ID"
echo "Current job name  : $JOB_NAME"
echo "Task index number : $TASK_ID"
echo "=========================================================="

source /broad/software/scripts/useuse
reuse GCC-5.2
reuse .libiconv-1.15

cd /medpop/afib/skhurshid/lvm_gwas/

/medpop/esp2/chaffin/bgenix/bgenix -g "/broad/ukbb/imputed_v3/ukb_imp_chr${SGE_TASK_ID}_v3.bgen" \
-incl-rsids "/medpop/afib/skhurshid/lvm_gwas/clumps/clump4_rsid.tsv" \
-i "/broad/ukbb/imputed_v3/ukb_imp_chr${SGE_TASK_ID}_v3.bgen.bgi" > chr${SGE_TASK_ID}.bgen

/medpop/afib/software/PLINK2.0/v18_Mar_2019/plink2 --bgen chr${SGE_TASK_ID}.bgen \
--sample /medpop/esp2/pradeep/UKBiobank/v2data/ukb708_imp_chr1_v2_s487406.sample \
--keep /medpop/afib/skhurshid/lvm_gwas/lvmi_seg_adjusted.tsv \
--score /medpop/afib/skhurshid/lvm_gwas/clumps/bolt_clumped4.tsv 1 2 3 'header' ignore-dup-ids cols=dosagesum,scoresums \
--out /medpop/afib/skhurshid/lvm_gwas/scores/seg_prs4/chr${SGE_TASK_ID}.score

rm chr${SGE_TASK_ID}.bgen
